/**
 * dsh-plugin-version-management — host entry (persistent plugin form).
 *
 * Capabilities:
 * - registers the `dsh_plugin_snapshot` / `dsh_plugin_restore` model tools;
 * - serves the settings-page API under /dsh-pvm/* HTTP routes;
 * - discovers the DSH profile directory and a writable snapshot root at
 *   runtime (no hard-coded machine paths — portable for other users).
 *
 * Restore semantics: full restore replaces third-party bundles/dependencies
 * with the snapshot state (official @deepseek-ai/* rows are kept); a subset
 * restore only touches the selected plugin names.
 */
import { mkdir, readFile, writeFile, readdir, stat } from 'node:fs/promises'
import { spawn } from 'node:child_process'
import { homedir } from 'node:os'
import path from 'node:path'

export const name = 'dsh-plugin-version-management'
export const inject = ['tools', 'webServer', 'timer']

const RESTORE_PS1 = [
  '# dsh-plugin-version-management offline restore launcher (ASCII only).',
  '# 1) runs dsh-plugin-restore-merge.js: backs up the profile package.json',
  '#    and rewrites its bundles/dependencies from dsh-plugin-snapshot.json;',
  '# 2) runs "pnpm install" inside the profile directory;',
  '# 3) prints fallback "dsh plugin add" commands for a manual reinstall.',
  '# Usage:',
  '#   powershell -NoProfile -ExecutionPolicy Bypass -File dsh-plugin-restore.ps1',
  'param(',
  '  [string]$SnapshotJson = ""',
  ')',
  '$ErrorActionPreference = "Continue"',
  '$Here = Split-Path -Parent $MyInvocation.MyCommand.Path',
  'if ($SnapshotJson -eq "") {',
  '  $SnapshotJson = Join-Path $Here "dsh-plugin-snapshot.json"',
  '}',
  'if (-not (Test-Path $SnapshotJson)) {',
  '  Write-Host "[ERROR] Snapshot JSON not found: $SnapshotJson"',
  '  exit 1',
  '}',
  '$MergeJs = Join-Path $Here "dsh-plugin-restore-merge.js"',
  'if (-not (Test-Path $MergeJs)) {',
  '  Write-Host "[ERROR] Merge script not found: $MergeJs"',
  '  exit 1',
  '}',
  '$node = $null',
  '$c = Get-Command node.exe -ErrorAction SilentlyContinue',
  'if ($c) { $node = $c.Source }',
  'if (-not $node) {',
  '  $c = Get-Command node -ErrorAction SilentlyContinue',
  '  if ($c) { $node = $c.Source }',
  '}',
  'if (-not $node) {',
  '  Write-Host "[ERROR] node.exe not found on PATH"',
  '  exit 1',
  '}',
  '& $node $MergeJs $SnapshotJson',
  'if ($LASTEXITCODE -ne 0) {',
  '  Write-Host "[ERROR] merge failed with exit code $LASTEXITCODE"',
  '  exit $LASTEXITCODE',
  '}',
  '$snap = Get-Content $SnapshotJson -Raw | ConvertFrom-Json',
  '$ProfileDir = $snap.profilePath',
  'if (-not (Test-Path $ProfileDir)) {',
  '  Write-Host "[ERROR] profile directory missing: $ProfileDir"',
  '  exit 1',
  '}',
  'Push-Location $ProfileDir',
  'try {',
  '  $pnpm = $null',
  '  $c = Get-Command pnpm.cmd -ErrorAction SilentlyContinue',
  '  if ($c) { $pnpm = $c.Source }',
  '  if (-not $pnpm) {',
  '    $c = Get-Command pnpm -ErrorAction SilentlyContinue',
  '    if ($c) { $pnpm = $c.Source }',
  '  }',
  '  if (-not $pnpm) {',
  '    $c = Get-Command corepack.cmd -ErrorAction SilentlyContinue',
  '    if ($c) { $pnpm = $c.Source }',
  '  }',
  '  if ($pnpm) {',
  '    & $pnpm install',
  '  } else {',
  '    Write-Host "[WARN] pnpm not found on PATH - package.json updated but plugins not installed yet"',
  '  }',
  '} finally {',
  '  Pop-Location',
  '}',
  'Write-Host ""',
  'Write-Host "Fallback - reinstall one by one (network required):"',
  'foreach ($p in $snap.dependencies.PSObject.Properties) {',
  '  $v = [string]$p.Value',
  '  $v = $v -replace "[\\^~]", ""',
  '  Write-Host ("  dsh plugin add " + $p.Name + "@" + $v)',
  '}',
  'Write-Host ""',
  'Write-Host "Done. Restart DSH to load the restored plugins."',
].join('\n')

const RESTORE_MERGE_JS = [
  '// dsh-plugin-version-management offline merge (run by dsh-plugin-restore.ps1).',
  '// Backs up the current profile package.json, then rewrites its bundle list',
  '// and dependencies from the snapshot. Current official @deepseek-ai/* rows',
  '// are kept; every third-party row comes from the snapshot.',
  '"use strict"',
  'const fs = require("fs")',
  'const path = require("path")',
  'const args = process.argv.slice(2)',
  'const snapshotPath = args[0]',
  'if (!snapshotPath || !fs.existsSync(snapshotPath)) {',
  '  console.error("[ERROR] snapshot json missing: " + snapshotPath)',
  '  process.exit(1)',
  '}',
  'function readJson(p, what) {',
  '  let text',
  '  try {',
  '    text = fs.readFileSync(p, "utf8")',
  '    if (text.charCodeAt(0) === 0xfeff) text = text.slice(1)',
  '    return JSON.parse(text)',
  '  } catch (e) {',
  '    console.error("[ERROR] cannot parse " + what + " " + p + ": " + e.message)',
  '    process.exit(1)',
  '  }',
  '}',
  'let snap = readJson(snapshotPath, "snapshot")',
  'if (!snap || snap.format !== "dsh-plugin-snapshot") {',
  '  console.error("[ERROR] not a dsh-plugin-snapshot file")',
  '  process.exit(1)',
  '}',
  'const profileDir = snap.profilePath',
  'if (!profileDir || !fs.existsSync(profileDir)) {',
  '  console.error("[ERROR] profile directory missing: " + profileDir)',
  '  process.exit(1)',
  '}',
  'const pkgPath = path.join(profileDir, "package.json")',
  'if (!fs.existsSync(pkgPath)) {',
  '  console.error("[ERROR] package.json missing: " + pkgPath)',
  '  process.exit(1)',
  '}',
  'let pkg = readJson(pkgPath, "package.json")',
  'const here = path.dirname(snapshotPath)',
  'const stamp = new Date().toISOString().slice(0, 19).replace(/[T:]/g, "-")',
  'const backup = path.join(here, "package.json.bak-" + stamp)',
  'fs.writeFileSync(backup, JSON.stringify(pkg, null, 2) + "\\n", "utf8")',
  'console.log("[OK] current package.json backed up to: " + backup)',
  'const bundles = (pkg.dsh && pkg.dsh.profile && Array.isArray(pkg.dsh.profile.bundles)) ? pkg.dsh.profile.bundles : []',
  'const deps = (pkg.dependencies && typeof pkg.dependencies === "object") ? pkg.dependencies : {}',
  'const baseBundles = bundles.filter(function (b) { return typeof b === "string" && b.indexOf("@deepseek-ai/") === 0 })',
  'const snapBundles = (Array.isArray(snap.bundles) ? snap.bundles : []).filter(function (b) { return typeof b === "string" && b.indexOf("@deepseek-ai/") !== 0 })',
  'pkg.dsh.profile.bundles = baseBundles.concat(snapBundles)',
  'const baseDeps = {}',
  'Object.keys(deps).forEach(function (k) { if (k.indexOf("@deepseek-ai/") === 0) baseDeps[k] = deps[k] })',
  'const newDeps = {}',
  'Object.keys(snap.dependencies || {}).forEach(function (k) { newDeps[k] = snap.dependencies[k] })',
  'Object.keys(baseDeps).forEach(function (k) { if (!(k in newDeps)) newDeps[k] = baseDeps[k] })',
  'pkg.dependencies = newDeps',
  'fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + "\\n", "utf8")',
  'console.log("[OK] package.json restored with " + snapBundles.length + " third-party bundle(s)")',
